//! Raw FFI bindings to the [Elastic Frame Protocol](https://github.com/agilecontent/efp) C API.
//!
//! This crate provides unsafe, low-level bindings generated by `bindgen`.
//! For a safe Rust wrapper, see the `efp` crate.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_is_nonzero() {
        let version = unsafe { efp_get_version() };
        assert_ne!(version, 0, "EFP version should be nonzero");
        let major = version >> 8;
        let minor = version & 0xff;
        eprintln!("EFP version: {major}.{minor}");
    }

    #[test]
    fn sender_lifecycle() {
        unsafe extern "C" fn noop_send(
            _data: *const u8,
            _size: usize,
            _stream_id: u8,
            _ctx: *mut std::ffi::c_void,
        ) {
        }

        unsafe {
            let handle = efp_init_send(1400, Some(noop_send), std::ptr::null_mut());
            assert_ne!(handle, 0, "efp_init_send should return a valid handle");

            let result = efp_end_send(handle);
            assert_eq!(result, 0, "efp_end_send should succeed");
        }
    }
}
